# Generated by Django 3.0 on 2019-12-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
