# Generated by Django 3.0 on 2019-12-16 10:24

from django.db import migrations, models
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_coming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_front_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.utils.upload_file_path),
        ),
    ]
